name: Deploy
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: tag
        run: echo ::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3 | cut -c 2-)
      - name: Updating version number to ${{ env.versionNumber }}
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./VERSION
          contents: ${{ steps.tag.outputs.tag }}
          write-mode: overwrite
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Build
        run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}